version: "3.8"
services:
  app:
    build: .
    depends_on:
      - database
    volumes:
      - .:/usr/local/src/app

  database:
    image: mariadb:10.4
    restart: always
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
