#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

$katana = new \Katana\Katana(
    new Symfony\Component\Console\Application,
);

$katana->handle(new \Katana\Config([
    'KATANA_CACHE_DIR'      => __DIR__ . '/_cache',
    'KATANA_CONTENT_DIR'    => __DIR__ . '/content',
    'KATANA_PUBLIC_DIR'     => __DIR__ . '/public',
]));